services:
  mysql:
    image: mysql:8
    container_name: habittracker-db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: habittracker
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  backend:
    build: ../backend
    container_name: habittracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/habittracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

volumes:
  mysql-data:
