services:
  mysql:
    image: mysql:8
    container_name: habittracker-db2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: habittracker
    ports:
      - "3307:3306"  # Puerto externo 3307 para evitar conflictos
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d  # ‚Üê Ruta relativa desde docker/
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      timeout: 20s
      retries: 10

  backend:
    build: ../backend
    container_name: habittracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/habittracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      mysql:
        condition: service_healthy
    restart: on-failure

volumes:
  mysql-data: