version: "3.9"
services:
  mysql:
    image: mysql:8
    container_name: habittracker-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: habittracker
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/init:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: habittracker-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/habittracker
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    container_name: habittracker-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql-data:
